language: r
cache: packages
latex: false
before-install:
  - R -e 'devtools::install_github("tensorflow")'
  - R -e 'tensorflow::install_tensorflow()'
matrix:
  include:
    - os: linux
      r: release
    - os: linux
      r: devel
    - os: osx
      r: release
